### ISSUE TITLE
Very big issue

### ISSUE THREAD

**Issue by AR-Student824** [hendersonyang/personal-website#1]
# Important issue

This website is not using a custom font, which is legally required, especially considering it is 2021. Please fix this before I contact lawyers to have this dealt with. Thanks for your compliance.

**Comment by AR-Student824** [comment]
# Update to this important issue
I will have to add on, to not use GitHub pages as it makes you do useless stuff just to get setup. Use Vercel or I will personally find you, grab your computer and delete this repository. Thanks for your compliance again 😃

**Comment by hendersonyang** [comment]
This is 2021 NOT 2031
Allowing the website to be accessible by users with slow internet connections is legally required

**Comment by hendersonyang** [comment]
> I will have to add on, to not use GitHub pages as it makes you do useless stuff just to get setup. Use Vercel or I will personally > find you, grab your computer and delete this repository. Thanks for your compliance again 😃
Setting up was a bit slow, but watch me create a new update in less than 30 seconds (supposedly)

**Comment by AR-Student824** [comment]
> This is 2021 NOT 2031
> Allowing the website to be accessible by users with slow internet connections is legally required

If you just put `, sans-serif` next to your font declaration, it'll use the system font UNTIL the new font is fully loaded. Easy.

**Comment by AR-Student824** [comment]
> > I will have to add on, to not use GitHub pages as it makes you do useless stuff just to get setup. Use Vercel or I will personally > find you, grab your computer and delete this repository. Thanks for your compliance again smiley
> > Setting up was a bit slow, but watch me create a new update in less than 30 seconds (supposedly)

On Vercel, it takes 2 seconds, not 30 seconds. Switch or say bye to this repo 😉
